### ISSUE TITLE
Can't download song (latest version)

### ISSUE THREAD

**Issue by erynze** [afkarxyz/SpotiFLAC#146]
https://open.spotify.com/track/69kFyd2ymmN4o7o4ozZCQS
This song. Gives me error that song is failed to fetch

**Comment by ciach1234** [comment]
Since the last few versions of the application I have not been able to download all materials. this is just an example...

> [05:11:26] [info] fetching track metadata...
> [05:11:26] [debug] url: https://open.spotify.com/track/1fgcjfkyqwokhwfefjtxp5?si=4bc543c951b24a4f
> [05:11:27] [success] fetched track: breathe (feat. jem cooke) - camelphat, cristoph, jem cooke
> [05:11:27] [debug] isrc: gb1101801976, duration: 193728ms
> [05:11:27] [info] fetch completed in 0.44s
> [05:11:27] [success] metadata fetched successfully
> [05:11:30] [info] starting download: breathe (feat. jem cooke) - camelphat, cristoph, jem cooke
> [05:11:33] [error] download failed

**Comment by afkarxyz** [comment]
fixed

**Comment by erynze** [comment]
> fixed

No, it wasn't fixed. Still gives me "failed to fetch metadata".
